# Generated by Django 2.0 on 2025-01-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('duration', models.CharField(max_length=255, verbose_name='Продолжительность')),
                ('transcribed_text', models.TextField(verbose_name='Текст')),
                ('synopsis_text', models.TextField(verbose_name='Краткое описание')),
                ('caller_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('caller_number', models.CharField(max_length=20, verbose_name='Номер')),
                ('caller_adr', models.CharField(max_length=150, verbose_name='Номер')),
                ('called_number', models.CharField(max_length=20, verbose_name='Номер')),
                ('link_inp_aud', models.TextField(max_length=255, verbose_name='Ссылка аудио')),
                ('link_out_text', models.TextField(max_length=255, verbose_name='Ссылка текст')),
                ('date_created', models.DateTimeField(verbose_name='Дата звонка')),
                ('date_of_transcribe', models.DateTimeField(verbose_name='Дата преобразования')),
                ('call_lenght_s', models.IntegerField(max_length=11, verbose_name='Продолжительность')),
            ],
            options={
                'db_table': 'transcribed_audio',
            },
        ),
    ]
